name: pronostik
description: "An app to predict the outcome of football matches."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
